plugins {
    id "com.android.application"
}

android {
    namespace "com.domi.worldcupobserver"
    compileSdk 35
    buildToolsVersion "35.0.0"

    defaultConfig {
        applicationId "com.domi.worldcupobserver"
        minSdk 23
        targetSdk 35
        versionCode 1
        versionName "1.0.0"
    }
}
